(function(root){
  const rio={
    trainerId:'rio',
    displayName:'リオ',
    themeColor:'#E4002B',
    personality:'energetic-hotblooded',
    assets:{
      hero:'./assets/trainers/rio/hero.webp',
      portrait:'./assets/trainers/rio/portrait.webp',
      levelUp:'./assets/trainers/rio/level-up.webp',
      expressions:{
        neutral:'./assets/trainers/rio/expressions/neutral.webp',
        smile:'./assets/trainers/rio/expressions/smile.webp',
        cheer:'./assets/trainers/rio/expressions/cheer.webp',
        blush:'./assets/trainers/rio/expressions/blush.webp',
        serious:'./assets/trainers/rio/expressions/serious.webp',
        tired:'./assets/trainers/rio/expressions/tired.webp',
        angry:'./assets/trainers/rio/expressions/angry.webp',
        achieved:'./assets/trainers/rio/expressions/achieved.webp'
      },
      chibi:{
        normal:'./assets/trainers/rio/chibi/normal.webp',
        cheer:'./assets/trainers/rio/chibi/cheer.webp',
        struggle:'./assets/trainers/rio/chibi/struggle.webp',
        rest:'./assets/trainers/rio/chibi/rest.webp',
        achieved:'./assets/trainers/rio/chibi/achieved.webp'
      }
    },
    states:{
      normal:'./assets/trainers/rio/expressions/neutral.webp',
      smile:'./assets/trainers/rio/expressions/smile.webp',
      cheer:'./assets/trainers/rio/expressions/cheer.webp',
      praise:'./assets/trainers/rio/expressions/achieved.webp',
      surprise:'./assets/trainers/rio/expressions/blush.webp',
      worry:'./assets/trainers/rio/expressions/serious.webp',
      fatigue:'./assets/trainers/rio/expressions/tired.webp',
      rest:'./assets/trainers/rio/chibi/rest.webp',
      achieved:'./assets/trainers/rio/expressions/achieved.webp',
      levelUp:'./assets/trainers/rio/level-up.webp'
    },
    fallbackStates:{praise:'achieved',surprise:'blush'}
  };
  root.MuscleMasterTrainers={rio};
})(typeof globalThis!=='undefined'?globalThis:this);
